### ISSUE TITLE
「Umiの特設ページ」へのリンクが古い（リンク切れ）

### ISSUE THREAD

**Issue by aiya000** [raryosu/Rin#18]
- 旧: https://nkmr6194.github.io/Umi/
- 新: https://ysakasin.github.io/Umi/

:cat2: authorさんが変わったのかにゃ？

**Comment by raryosu** [comment]
@aiya000 さん
Issueありがとうございます．

#19 にて上記修正いたしました．
（Author の サカシンさんがGitHubのIDを変更されたようですね）

後ほどHonokaにもPRを出そうと思います．
（ちなみに https://github.com/windyakin/Honoka/pull/40 はPRの向き先を間違えただけです．）

**Comment by aiya000** [comment]
:+1:
